#!/usr/bin/env python
a = int(input("a="))
b = int(input("b="))
#Entrer a et b

compteur = a
 
somme = 0
 
while compteur < b:
	 print (compteur)
	 if compteur%5==0:
		 print (compteur)
		 somme = somme + compteur
		 compteur=compteur+1
   
print (somme)
   


ecrivez un script qui affiche la valeur de la force de gravitation s'exerçant entre deux masses de 10000kg, pour des distances qui
augmentent suivant une progression géométrique de raison 2, entre deux valeurs de distance. La force de gravitation est régie par la 
formule : F=6,67.10^-11.m.m'/d²
