#!/usr/bin/env python
a= input("a = ") 
k=int(a)
#Entier
b= input("b = ")
z=int(b)
#Entrer les bornes 
valeur=0 
#La somme

for x in range (k,z): #pour x entre les bornes
  if x%5==0 : #si le reste est égal à 0 alors
	  valeur=valeur+x #la somme égale à
print (valeur) #affiche la valeur finale
